### ISSUE TITLE
Whether to support the Chinese

### ISSUE THREAD

**Issue by oakpip** [amilcar-sr/JustifiedTextView#1]

**Comment by amilcar-sr** [comment]
I think the library wouldn't have troubles with chinese characters... but I haven't really tested it. If you have troubles using chinese characters please let me know what are you seeing and I'll try to make a fix :)

**Comment by oakpip** [comment]
I test your lib, it's not support chinese characters, please fix it.

**Comment by amilcar-sr** [comment]
ok, I did a fix (sorry it took so long) give it a try again if you have the time and let me know if it works now.
