### ISSUE TITLE
Formatted string loses its html tags

### ISSUE THREAD

**Issue by AlexandruDev** [amilcar-sr/JustifiedTextView#5]
This library works very well but it has 1 downside - the fact that I lose all formatting from my string ( bold, italic, spaces between paragraphs ). 

`JustifiedTextView textView1 = (JustifiedTextView) findViewById(R.id.textView_1);
        textView1.setText(StringHtmlUtils.fromHtml(getResources().getString(R.string.myText_1)));`

` <com.codesgood.views.JustifiedTextView
                    android:id="@+id/textView_1"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="8dp"
                    android:textSize="16sp" />`

Any idea?

**Comment by amilcar-sr** [comment]
You're right, I'm going to fix this as soon as I can. Thanks for reporting it! 😄

**Comment by amilcar-sr** [comment]
Right now the view doesn't support HTML becasue of a refactor... but I'll do my best to release a new version of the library that supports it. I'll close this for the moment becasue no longer applies.
