### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by YuhApps** [amilcar-sr/JustifiedTextView#6]
I got the issue when setText with Strings in HTML format. It works fine with oridinary Strings.

java.lang.StringIndexOutOfBoundsException: length=0; index=0 at com.codesgood.views.JustifiedTextView.onLayout(JustifiedTextView.java:90)

**Comment by amilcar-sr** [comment]
I'm going to make a refactor soon and I'll make sure to fix this issue. Thanks for reporting it! 😄

**Comment by amilcar-sr** [comment]
Right now the view doesn't support HTML becasue of a refactor... but I'll do my best to release a new version of the library that supports it. I'll close this for the moment becasue no longer applies.
